Update to Freedesktop SDK 22.08
flathub/io.github.endless_sky.endless_sky pull request #12
Opened 2022-10-04 19:48 UTC by quyykk

This PR simply updates the SDK version to 22.08, mainly for the latest version of SDL.

The scons build rules broke when I updated the SDK version, so I used `flatpak-pip-generator` to create a separate json.

2022-10-04 20:32 UTC, quyykk commented
I'm not sure what's wrong with this, but the game doesn't start anymore:

```
(SDL message: "No available video device")
```

2022-10-04 20:36 UTC, Pointedstick requested changes

2022-10-04 20:36 UTC, Pointedstick commented on io.github.endless_sky.endless_sky.json
> +		"python3-scons.json",
Indentation is off (we use spaces, not tabs)

2022-10-04 20:36 UTC, Pointedstick commented on io.github.endless_sky.endless_sky.json
> +        "--share=ipc",
These a good changes, but not relevant to this PR. Can you do them in another one?

2022-10-04 20:36 UTC, Pointedstick commented on python3-scons.json
> +{
Moving this to a separate file doesn't seem necessary; why can't we keep it inline?

2022-10-04 20:36 UTC, Pointedstick commented on python3-scons.json
> +            "url": "https://files.pythonhosted.org/packages/1a/e1/7fad50e1baa7068e3e2382b11c4d00190238798d62bfa6bbfa8619c19f39/SCons-4.4.0-py3-none-any.whl",
We shouldn't change the location we're getting `scons` from. It should remain an official archive location.

2022-10-04 20:39 UTC, quyykk commented on io.github.endless_sky.endless_sky.json
> +        "--share=ipc",
sure thing

2022-10-04 20:39 UTC, quyykk commented on python3-scons.json
> +{
idk I followed the guidelines. I'll keep it inline.

2022-10-04 20:40 UTC, quyykk commented on python3-scons.json
> +            "url": "https://files.pythonhosted.org/packages/1a/e1/7fad50e1baa7068e3e2382b11c4d00190238798d62bfa6bbfa8619c19f39/SCons-4.4.0-py3-none-any.whl",
That's the official package location for `pip` packages. Is that still fine?

2022-10-04 20:47 UTC, Pointedstick commented on python3-scons.json
> +            "url": "https://files.pythonhosted.org/packages/1a/e1/7fad50e1baa7068e3e2382b11c4d00190238798d62bfa6bbfa8619c19f39/SCons-4.4.0-py3-none-any.whl",
We shouldn't use `pip` during a build process at all. :) We should download the source from its official location, as we currently do.

2022-10-04 20:49 UTC, quyykk commented
> I'm not sure what's wrong with this, but the game doesn't start anymore:
> 
> ```
> (SDL message: "No available video device")
> ```

Seems to be a glew issue :confused: Yet another reason to stop using glew.

2022-10-04 20:51 UTC, Pointedstick commented
Maybe fixed with the change in the new release? Maybe we should wait until Anitya notices it and updates the manifest, and then it'll be fixed automatically.

2022-10-04 20:59 UTC, quyykk commented
Unfortunately no. I just tried building 0.9.15 manually and yup, same error.

2022-10-05 08:07 UTC, quyykk commented on python3-scons.json
> +            "url": "https://files.pythonhosted.org/packages/1a/e1/7fad50e1baa7068e3e2382b11c4d00190238798d62bfa6bbfa8619c19f39/SCons-4.4.0-py3-none-any.whl",
But it's way easier to install python packages through pip instead of installing them manually :)

2022-10-05 08:14 UTC, Pointedstick commented on python3-scons.json
> +            "url": "https://files.pythonhosted.org/packages/1a/e1/7fad50e1baa7068e3e2382b11c4d00190238798d62bfa6bbfa8619c19f39/SCons-4.4.0-py3-none-any.whl",
Like I said, it's not good practice to do something like that during a formal build process. It's volatile, things can change from under you... it's just not accepted practice for high quality build system code.

2022-10-05 12:49 UTC, quyykk commented
Good news, it seems like it's not a glew issue after all! I can't run the flatpak if I build it myself, but if I install the test build above it works! (but since this is 0.9.14 on Wayland, it fails with that glew error).

2022-10-10 02:05 UTC, Pointedstick commented
bot, build.

2022-10-10 02:48 UTC, Pointedstick approved these changes
Thanks!

2022-10-10 02:48 UTC, merged